version: "3.9"
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    restart: always
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
       - mongodbdata:/data/db
    restart: always
volumes:
    mongodbdata:
